Modified border radius all button variants
brave/leo pull request #319
Opened 2023-07-06 22:31 UTC by nullhook

All button variants now have a constant border radius that is half of the button's height.

2023-07-06 23:23 UTC, petemill requested changes
Needs to at least look the same as current master:
<img width="1057" alt="image" src="https://github.com/brave/leo/assets/741836/3235561b-bd02-418a-90f9-11fedf4415d2">

2023-07-06 23:41 UTC, fallaciousreasoning commented
This might be related, but the focus outline for the jumbo hero button doesn't look quite right:
![image](https://github.com/brave/leo/assets/7678024/8a7ac533-30d8-41fb-8b4c-8888797b6133)

The focus outlines on the `plain` & `plain-faint` buttons aren't the same either, but this is present in main (so I don't think we need to fix it here).
`plain`
![image](https://github.com/brave/leo/assets/7678024/c48e780b-5a48-4314-9cf5-27f35bc0928c)
`plain-faint`
![image](https://github.com/brave/leo/assets/7678024/687a96e4-c69a-4b19-8b05-64ec9f6e1390)

Thanks for working on this @nullhook!

2023-07-06 23:44 UTC, fallaciousreasoning commented on src/components/button/button.svelte
> +    border-radius: 24px;
Inspecting the button in devtools, the button is `60px` high, so should this be `30px`?

2023-07-06 23:46 UTC, fallaciousreasoning approved these changes
LGTM, pending the fix for the jumbo buttons (which I think the `border-radius` tweak will do)

2023-07-07 00:12 UTC, fallaciousreasoning commented on src/components/button/button.svelte
I think we're still setting the border-radius to var(--leo-radius-full) on line 103. It can probably be removed.

2023-07-07 00:32 UTC, fallaciousreasoning approved these changes
LGTM, and the Storybook looks good!

Let's land it
![image](https://github.com/brave/leo/assets/7678024/fac43c47-8b32-4156-b3de-09e3bae41acf)

2023-07-07 18:39 UTC, petemill approved these changes

2023-07-09 20:47 UTC, merged