[Icons]: Update icons from Figma
brave/leo pull request #619
Opened 2024-04-04 08:09 UTC by brave-support-admin

> @brave/leo@0.0.1 update-icons
> node ./src/scripts/update-icons.js

Ignoring icon rainbow-color.svg because:
- has a raster image element
Ignoring icon bitcoin.com-color.svg because:
- has a raster image element
Ignoring icon daum-color.svg because:
- has a raster image element

2024-04-04 15:49 UTC, aguscruiz commented
Yeah, just for different icons in case we ever want to change the design of
one without affecting the other

On Thu, Apr 4, 2024, 12:12 Jacob Lamont ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On icons/news-health.svg
> <https://github.com/brave/leo/pull/619#discussion_r1551873735>:
>
> @aguscruiz <https://github.com/aguscruiz>, is this intentionally a
> duplicate of hearts.svg?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/brave/leo/pull/619#pullrequestreview-1980226220>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADYBOZSQ5MB3OTPX5BTH2FTY3VUURAVCNFSM6AAAAABFWYMGM6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSOBQGIZDMMRSGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-04 15:58 UTC, AlanBreck approved these changes

2024-04-05 15:46 UTC, AlanBreck commented on icons/price-tag.svg
@aguscruiz, is the background intentional?

2024-04-05 17:08 UTC, aguscruiz commented on icons/price-tag.svg
Ugh, no, not intentional, must've clicked something by mistake. Fixed now

2024-04-08 15:40 UTC, AlanBreck commented on icons/price-tag.svg
@aguscruiz, still didn't resolve it.

2024-04-08 17:03 UTC, aguscruiz commented on icons/price-tag.svg
Hmmm, try one last time, I unchecked an export thing but there's nothing there that would show a bg

<img width="485" alt="image" src="https://github.com/brave/leo/assets/15734630/8ecc1191-d133-4912-bd46-dd71466305ba">

2024-04-08 18:49 UTC, AlanBreck approved these changes

2024-04-08 18:50 UTC, AlanBreck commented on icons/price-tag.svg
That icon is no longer included in the PR.

2024-04-09 15:26 UTC, AlanBreck commented on icons/country-au.svg
@aguscruiz, something looks fishy here.

2024-04-09 15:26 UTC, AlanBreck commented on icons/price-tag.svg
@aguscruiz ☝️

2024-04-09 16:25 UTC, aguscruiz commented on icons/price-tag.svg
Ok no problem, it's not used anywhere

2024-04-09 16:28 UTC, aguscruiz commented on icons/country-au.svg
Fixed, there was another broken flag and fixed that one too

2024-04-09 16:56 UTC, AlanBreck requested changes
@aguscruiz, now the flags are gone.

2024-04-09 17:12 UTC, AlanBreck approved these changes

2024-04-09 17:15 UTC, merged