[SegmentedControl]: Updated styles for pill background and hover background
brave/leo pull request #754
Opened 2024-07-26 17:24 UTC by aguscruiz

There was an issue that surfaced in wallet, where the segmented control had very low contrast. I checked and it was different from figma, so here's an update

- themable/10 for component background
- container/highlight for hover state

<img width="785" alt="image" src="https://github.com/user-attachments/assets/c34d2f12-956e-4b31-bd03-89dce63468da">

2024-07-26 18:21 UTC, AlanBreck approved these changes

2024-07-26 18:24 UTC, AlanBreck requested changes
I approved too quickly. It's complaining that `--leo-color-gray-10` doesn't exist...

2024-07-26 19:41 UTC, AlanBreck approved these changes

2024-07-28 22:57 UTC, fallaciousreasoning commented
Is this intentional? There doesn't seem to be a background in light mode?
![image](https://github.com/user-attachments/assets/2391ac9b-94db-4a01-a9be-2cde24c41a0f)

2024-07-28 22:57 UTC, fallaciousreasoning approved these changes

2024-07-29 11:23 UTC, aguscruiz commented
@fallaciousreasoning there is, but the preview panel background is the same. I was talking with @AlanBreck about it, seems that the pannel is using page/background for bg instead of container/background. He has a fix

2024-07-29 11:25 UTC, merged