[Rennovate]: Enable automerge for devDependencies, minor and patches
brave/leo pull request #837
Opened 2024-09-18 08:00 UTC by fallaciousreasoning

I was talking to @thypon about disabling dependabot updates for `/examples/example-ui-react` or setting them to automerge and thought, why not set it for a bunch of things we normally merge anyway. If anything breaks, the build in Nala should fail, which will prevent the automerge.

Interested in hearing some thoughts on this (and whether its a bad idea).

2024-09-18 08:03 UTC, fallaciousreasoning commented on .github/renovate.json
> +        "peerDependencies"
if we don't disable peerDependencies, it tries to set React to latest, which isn't compatible with brave-core (most of the time)

2024-09-18 08:03 UTC, fallaciousreasoning commented on .github/renovate.json
> +        "patch"
I'm not opposed to adding `"digest"` and `"pin"` to this list, but I'm a bit hazy on exactly what they mean.

The build will fail if something goes wrong here.

2024-09-18 08:04 UTC, fallaciousreasoning commented on .github/renovate.json
> +        "devDependencies"
ditto

2024-09-18 17:05 UTC, AlanBreck approved these changes

2024-09-19 16:22 UTC, diracdeltas requested changes
my 2 concerns with this are making sure `npm audit` and the Socket checks are passing before the automerge happens (need to make sure those things are set up as blocking github checks in this repo and that the automerge doesn't override that); and that we set a delay of ~1 week before automerge happens so there is time to detect if these updates are malicious.

2024-10-16 02:29 UTC, fallaciousreasoning commented
@diracdeltas I've set up the `audit` check in https://github.com/brave/leo/pull/871 but as per our messages, I've disabled it for `rennovate` and `dependabot` PRs. Is that going to be a problem?

2024-10-18 02:11 UTC, diracdeltas approved these changes

2024-10-21 01:35 UTC, fallaciousreasoning commented
Ran the rennovate config validator, and it seems happy, so I'm going to merge this.
![image](https://github.com/user-attachments/assets/22c96bcc-5789-437f-b2ff-4be9ed7cc1d7)


cc @AlanBreck if we should keep an eye on whether dependabot/rennovate PRs are still landing.

2024-10-21 01:36 UTC, merged